
"""
review_series_protocols.py
==========================

Prevalence-based protocol review for per-series TSV inventories produced by
query_series.py.

This script is intentionally focused on protocol review, not BIDS conversion.

It writes four review TSVs:
  01_sequence_prevalence.tsv
  02_subject_protocol_review.tsv
  03_protocol_family_summary.tsv
  04_excluded_series_audit.tsv

Modes
-----
detect:
    Use a concatenated TSV containing many subjects/sessions to discover core
    research sequences and protocol families.

identify:
    Use an individual subject/session TSV and compare it to an existing
    protocol family summary generated by detect mode.

Examples
--------
Detect protocol families from a concatenated TSV:

    python review_series_protocols.py \
        --input all_ses-001_series.tsv \
        --output-dir review_COMPASS \
        --concat \
        --mode detect \
        --site COMPASS

Identify one subject against existing families:

    python review_series_protocols.py \
        --input sub-CC001_ses-001_series.tsv \
        --output-dir review_sub-CC001 \
        --mode identify \
        --protocol-summary review_COMPASS/03_protocol_family_summary.tsv

Notes
-----
- Keeps source-like ORIGINAL rows.
- Excludes derived rows, localizers/scouts, MoCoSeries, DWI scalar maps,
  MPR reformats, mIP/MNIP, PhoenixZIPReport, and other scanner reports.
- Protects MPRAGE/MEMPRAGE/Sag_T1_3D_MPRAGE_Wave as source T1w.
- Uses prevalence rather than exact sequence-set differences to avoid creating
  fake protocol variants from rare clinical/add-on scans.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Set, Tuple


# -----------------------------
# I/O
# -----------------------------

def read_tsv(path: Path) -> Tuple[List[dict], List[str]]:
    with path.open(newline="", encoding="utf-8", errors="replace") as f:
        reader = csv.DictReader(f, delimiter="\t")
        rows = list(reader)
        if reader.fieldnames is None:
            raise SystemExit(f"ERROR: {path} does not look like a TSV with a header")
        return rows, list(reader.fieldnames)


def write_tsv(path: Path, rows: Sequence[dict], fieldnames: Sequence[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, delimiter="\t")
        writer.writeheader()
        for row in rows:
            writer.writerow({k: row.get(k, "") for k in fieldnames})


def get(row: dict, key: str) -> str:
    return (row.get(key) or "").strip()


def as_int(value, default: int = 999999) -> int:
    try:
        return int(float(str(value)))
    except Exception:
        return default


def norm_text(value: str) -> str:
    value = (value or "").casefold()
    value = re.sub(r"[_\-.]+", " ", value)
    value = re.sub(r"\s+", " ", value).strip()
    return value


# -----------------------------
# Classification rules
# -----------------------------

def image_type_tokens(row: dict) -> Set[str]:
    return {t.casefold() for t in get(row, "image_type").split("\\") if t}


def is_original(row: dict) -> bool:
    return "original" in image_type_tokens(row)


def is_derived(row: dict) -> bool:
    return "derived" in image_type_tokens(row)


def is_true_mpr_reformat(row: dict) -> bool:
    """
    Detect true MPR/reformat derivatives without accidentally excluding MPRAGE.

    Examples:
      Sag_T1_3D_MPRAGE_Wave          -> source T1w
      Sag_T1_3D_MPRAGE_Wave_MPR_Ax   -> derived reformat
      Sag_T1_3D_MPRAGE_Wave_MPR Cor  -> derived reformat
    """
    desc = get(row, "series_description")
    desc_norm = norm_text(desc)
    toks = image_type_tokens(row)

    explicit_mpr_suffix = bool(
        re.search(
            r"(^|[_\s-])MPR([_\s-]|$)|_MPR_| Ax MPR| Cor MPR| Tra MPR| Sag MPR",
            desc,
            re.IGNORECASE,
        )
    )

    if "mprage" in desc_norm or "memprage" in desc_norm:
        return explicit_mpr_suffix

    if explicit_mpr_suffix:
        return True

    if "mpr" in toks or "resampled" in toks:
        return True

    return False


def excluded_reason(row: dict) -> str:
    """
    Return empty string when row is eligible as source-like ORIGINAL.
    Otherwise return the reason it should be excluded from protocol discovery.
    """
    desc = get(row, "series_description")
    desc_norm = norm_text(desc)
    toks = image_type_tokens(row)

    if not is_original(row):
        return "not ORIGINAL image_type"

    if re.search(r"^(Loc|AAHScout|AAScout|Localizer|Scout|Survey)", desc, re.IGNORECASE):
        return "localizer/scout"

    if "mocoseries" in desc_norm:
        return "MoCo derivative"

    if re.search(r"PhoenixZIPReport|Visage\s+Presentation|DoseReport|Report", desc, re.IGNORECASE):
        return "scanner report"

    if is_true_mpr_reformat(row):
        return "MPR/reformat derivative"

    if re.search(r"(_ADC$|_FA$|_ColFA$|_TRACEW$|_TENSOR(?:_B0)?$)", desc, re.IGNORECASE):
        return "DWI derivative scalar/map"

    if any(t in toks for t in {"adc", "fa", "tracew", "tensor", "tensor_b0"}):
        return "DWI derivative image_type"

    if re.search(r"mIP|MNIP", desc, re.IGNORECASE):
        return "mIP/MNIP derivative"

    if re.search(r"PhysioLog|EvaSeries_GLM|Mean_&_t-Maps|Design$|relCBF|Perfusion_Weighted|WIP SOURCE", desc, re.IGNORECASE):
        return "known derivative/non-image output"

    if is_derived(row):
        return "DERIVED image_type"

    return ""


def canonical_sequence(row: dict) -> str:
    """
    Canonical protocol-comparison label. This is not necessarily final BIDS.
    """
    desc = get(row, "series_description")
    desc_norm = norm_text(desc)

    # T1w source families.
    if re.search(r"(MPRAGE|MEMPRAGE|Sag_T1|T1_3D|sT1W|T1w|BRAVO)", desc, re.IGNORECASE):
        if re.search(r"BRAVO|Pre Ax T1|Post Ax T1|FLASH", desc, re.IGNORECASE):
            return f"CLINICAL_OR_EXTRA:{desc}"
        return "T1w_MPRAGE_Wave" if "wave" in desc_norm else "T1w_MPRAGE"

    # Anatomical.
    if re.search(r"FLAIR", desc, re.IGNORECASE):
        return "FLAIR"
    if re.search(r"(^|[_\s])T2($|[_\s])|Ax_T2| T2", desc, re.IGNORECASE):
        return "T2w"

    # SWI-like. Kept as optional/reviewable protocol content, not auto-BIDS.
    if re.search(r"SWI", desc, re.IGNORECASE):
        if re.search(r"Mag", desc, re.IGNORECASE):
            return "SWI_Mag"
        if re.search(r"Pha", desc, re.IGNORECASE):
            return "SWI_Pha"
        return "SWI"

    # Fieldmaps by target group and direction. Collapse minor variant suffixes.
    if re.search(r"FieldMap|SpinEchoFieldMap", desc, re.IGNORECASE):
        target = "unknown"
        if re.search(r"Diff|DWI|DTI|dMRI", desc, re.IGNORECASE):
            target = "dwi"
        elif re.search(r"rsfMRI|REST|rfMRI", desc, re.IGNORECASE):
            target = "rest"
        elif re.search(r"fMRI|bold", desc, re.IGNORECASE):
            target = "task"

        direction = "UNK"
        if re.search(r"_AP($|_)|(^|[_\s])AP($|[_\s])", desc, re.IGNORECASE):
            direction = "AP"
        elif re.search(r"_PA($|_)|(^|[_\s])PA($|[_\s])", desc, re.IGNORECASE):
            direction = "PA"
        elif re.search(r"_LR($|_)|(^|[_\s])LR($|[_\s])", desc, re.IGNORECASE):
            direction = "LR"
        elif re.search(r"_RL($|_)|(^|[_\s])RL($|[_\s])", desc, re.IGNORECASE):
            direction = "RL"

        return f"FieldMap_{target}_{direction}"

    # DWI. Collapse small naming variants but preserve old/clinical vs modern research families.
    if re.search(r"(DWI|Diff|DTI|DIF|dMRI)", desc, re.IGNORECASE):
        if re.search(r"Ax[_\s]?DWI", desc, re.IGNORECASE):
            return "DWI_Ax_clinical_or_old"
        if re.search(r"1\.5mm|1p5", desc, re.IGNORECASE):
            return "DWI_3shell_1p5"
        if re.search(r"1p8|1\.8iso|32b0", desc, re.IGNORECASE):
            return "DWI_3shell_1p8"
        if re.search(r"2p0|2\.0iso", desc, re.IGNORECASE):
            return "DWI_3shell_2p0"
        if re.search(r"AP", desc, re.IGNORECASE):
            return "DWI_AP"
        if re.search(r"PA", desc, re.IGNORECASE):
            return "DWI_PA"
        if re.search(r"LR", desc, re.IGNORECASE):
            return "DWI_LR"
        if re.search(r"RL", desc, re.IGNORECASE):
            return "DWI_RL"
        return "DWI_other"

    # Functional tasks/rest.
    if re.search(r"(fMRI|rsfMRI|REST|LANGUAGE|TENNIS|MOCA|bold|rfMRI|EMOTION|HAND)", desc, re.IGNORECASE):
        upper = desc.upper()
        if "LANGUAGE" in upper:
            return "BOLD_task-language"
        if "TENNIS" in upper:
            return "BOLD_task-tennis"
        if "EMOTION" in upper:
            return "BOLD_task-emotion"
        if "HAND" in upper:
            return "BOLD_task-hand"
        if "REST" in upper or "RSFMRI" in upper or "RFMRI" in upper or "BOLD_M600" in upper:
            return "BOLD_task-rest"
        return "BOLD_other"

    # Known clinical/extra examples.
    if re.search(r"(FLASH|Pre Ax T1|Post Ax T1)", desc, re.IGNORECASE):
        return f"CLINICAL_OR_EXTRA:{desc}"

    return f"OTHER:{desc}"


def modality_group(seq: str) -> str:
    if seq.startswith("T1w"):
        return "anat_t1w"
    if seq == "FLAIR":
        return "anat_flair"
    if seq == "T2w":
        return "anat_t2w"
    if seq.startswith("SWI"):
        return "swi_optional"
    if seq.startswith("FieldMap"):
        return "fmap"
    if seq.startswith("DWI_3shell"):
        return "dwi_research"
    if seq.startswith("DWI_Ax"):
        return "dwi_old_or_clinical"
    if seq.startswith("DWI"):
        return "dwi"
    if seq.startswith("BOLD"):
        return "func"
    if seq.startswith("CLINICAL_OR_EXTRA"):
        return "clinical_extra"
    return "other"


def is_research_candidate(seq: str) -> bool:
    """
    Determines whether a kept source-like series can contribute to core protocol discovery.

    Rare clinical extras are still listed in the subject review, but they do not define
    protocol families by default.
    """
    if seq.startswith("CLINICAL_OR_EXTRA:") or seq.startswith("OTHER:"):
        return False
    return True


# -----------------------------
# Subject grouping and protocol logic
# -----------------------------

def prepare_rows(rows: Sequence[dict]) -> Tuple[List[dict], List[dict]]:
    kept, excluded = [], []

    for row in rows:
        reason = excluded_reason(row)
        if reason:
            excluded.append({
                "subject": get(row, "subject"),
                "session": get(row, "session"),
                "scan_date": get(row, "scan_date"),
                "series_number": get(row, "series_number"),
                "series_description": get(row, "series_description"),
                "protocol_name": get(row, "protocol_name"),
                "image_type": get(row, "image_type"),
                "n_files": get(row, "n_files"),
                "exclude_reason": reason,
            })
            continue

        rr = dict(row)
        seq = canonical_sequence(row)
        rr["canonical_sequence"] = seq
        rr["modality_group"] = modality_group(seq)
        rr["research_candidate"] = "yes" if is_research_candidate(seq) else "no"
        kept.append(rr)

    return kept, excluded


def group_by_subject(rows: Sequence[dict]) -> Dict[Tuple[str, str], List[dict]]:
    grouped = defaultdict(list)
    for row in rows:
        grouped[(get(row, "subject"), get(row, "session"))].append(row)

    for key in grouped:
        grouped[key].sort(key=lambda r: (
            get(r, "scan_date"),
            as_int(get(r, "series_number")),
            get(r, "series_time"),
            get(r, "series_description"),
        ))

    return dict(grouped)


def build_subject_reviews(grouped: Dict[Tuple[str, str], List[dict]]) -> List[dict]:
    subject_rows = []

    for (subject, session), rows in sorted(grouped.items(), key=lambda kv: (
        get(kv[1][0], "scan_date") if kv[1] else "",
        kv[0][0],
        kv[0][1],
    )):
        research = sorted({r["canonical_sequence"] for r in rows if r["research_candidate"] == "yes"})
        all_kept = sorted({r["canonical_sequence"] for r in rows})
        optional_extra = sorted(set(all_kept) - set(research))

        subject_rows.append({
            "subject": subject,
            "session": session,
            "scan_date": get(rows[0], "scan_date") if rows else "",
            "n_original_kept_rows": len(rows),
            "n_research_candidate_sequences": len(research),
            "research_sequence_set": " + ".join(research),
            "noncore_extra_sequence_set": " + ".join(optional_extra),
            "all_kept_sequence_set": " + ".join(all_kept),
            "ordered_kept_series": " | ".join(
                f"{get(r, 'series_number')}:{get(r, 'series_description')}->{r['canonical_sequence']}"
                for r in rows
            ),
        })

    return subject_rows


def build_sequence_prevalence(subject_rows: Sequence[dict], kept_rows: Sequence[dict], core_threshold: float) -> List[dict]:
    total = len(subject_rows)
    seq_subjects = defaultdict(set)
    seq_dates = defaultdict(list)
    seq_raw = defaultdict(Counter)

    for subject_row in subject_rows:
        subject = subject_row["subject"]
        date = subject_row["scan_date"]
        seqs = subject_row["research_sequence_set"].split(" + ") if subject_row["research_sequence_set"] else []
        for seq in seqs:
            seq_subjects[seq].add(subject)
            if date:
                seq_dates[seq].append(date)

    for row in kept_rows:
        if row.get("research_candidate") == "yes":
            seq_raw[row["canonical_sequence"]][get(row, "series_description")] += 1

    output = []
    for seq, subjects in sorted(seq_subjects.items(), key=lambda kv: (-len(kv[1]), kv[0])):
        pct = 100.0 * len(subjects) / total if total else 0.0
        if pct >= core_threshold * 100:
            role = "core"
        elif pct >= 50:
            role = "common_noncore"
        elif pct >= 20:
            role = "variant_specific"
        else:
            role = "rare_optional_or_clinical"

        output.append({
            "canonical_sequence": seq,
            "modality_group": modality_group(seq),
            "n_subjects": len(subjects),
            "n_total_subjects": total,
            "prevalence_pct": round(pct, 1),
            "role": role,
            "first_seen": min(seq_dates[seq]) if seq_dates[seq] else "",
            "last_seen": max(seq_dates[seq]) if seq_dates[seq] else "",
            "subjects": " | ".join(sorted(subjects)),
            "raw_series_descriptions": " | ".join(f"{d} ({c})" for d, c in seq_raw[seq].most_common()),
        })

    return output


def assign_protocol_family(seq_set: str) -> str:
    """
    Conservative family assignment. This avoids creating a new variant for one-off extras.
    """
    seqs = set(seq_set.split(" + ")) if seq_set else set()

    if len(seqs) <= 3:
        return "INCOMPLETE_OR_OFFPROTOCOL"

    modern_fmaps = {
        "FieldMap_task_AP",
        "FieldMap_task_PA",
        "FieldMap_rest_AP",
        "FieldMap_rest_PA",
        "FieldMap_dwi_AP",
        "FieldMap_dwi_PA",
    }
    modern_tasks = {"BOLD_task-language", "BOLD_task-tennis", "BOLD_task-rest"}

    if modern_fmaps.issubset(seqs) and modern_tasks.issubset(seqs) and "DWI_3shell_1p8" in seqs:
        return "V2_MODERN_FIELDMAP_1P8"

    if "DWI_3shell_1p5" in seqs and "BOLD_task-rest" in seqs:
        return "V1_OLD_1P5"

    return "REVIEW_MIXED_OR_EXTRA"


def build_family_summary(subject_rows: Sequence[dict], core_threshold: float, site: str) -> Tuple[List[dict], List[dict]]:
    grouped = defaultdict(list)

    for row in subject_rows:
        family = assign_protocol_family(row["research_sequence_set"])
        if site:
            family = f"{site}_{family}"
        row["protocol_family"] = family
        grouped[family].append(row)

    family_rows, sequence_rows = [], []

    for family, members in sorted(grouped.items(), key=lambda kv: (
        min((m["scan_date"] for m in kv[1] if m["scan_date"]), default=""),
        kv[0],
    )):
        n = len(members)
        sets = [
            set(m["research_sequence_set"].split(" + ")) if m["research_sequence_set"] else set()
            for m in members
        ]
        union = sorted(set.union(*sets)) if sets else []
        counts = Counter()
        for seq_set in sets:
            counts.update(seq_set)

        core_100 = [seq for seq in union if counts[seq] == n]
        core_threshold_seqs = [seq for seq in union if n and counts[seq] / n >= core_threshold]
        noncore = [seq for seq in union if seq not in core_threshold_seqs]
        dates = sorted(m["scan_date"] for m in members if m["scan_date"])

        family_rows.append({
            "protocol_family": family,
            "n_subjects": n,
            "first_scan_date": dates[0] if dates else "",
            "last_scan_date": dates[-1] if dates else "",
            "subjects": " | ".join(f"{m['subject']}:{m['scan_date']}" for m in members),
            "core_sequences_100pct": " + ".join(core_100),
            f"core_sequences_{int(core_threshold * 100)}pct": " + ".join(core_threshold_seqs),
            "noncore_optional_or_extra_sequences": " + ".join(noncore),
        })

        for seq in union:
            sequence_rows.append({
                "protocol_family": family,
                "canonical_sequence": seq,
                "modality_group": modality_group(seq),
                "n_subjects_with_sequence": counts[seq],
                "n_subjects_in_family": n,
                "prevalence_pct": round(100.0 * counts[seq] / n, 1) if n else 0.0,
                "role_in_family": (
                    "core_100pct" if counts[seq] == n else
                    f"core_{int(core_threshold * 100)}pct" if n and counts[seq] / n >= core_threshold else
                    "noncore_optional_or_extra"
                ),
            })

    return family_rows, sequence_rows


def write_detect_outputs(
    output_dir: Path,
    kept_rows: Sequence[dict],
    excluded_rows: Sequence[dict],
    subject_rows: List[dict],
    prevalence_rows: Sequence[dict],
    family_rows: Sequence[dict],
    core_threshold: float,
) -> None:
    # 01
    write_tsv(output_dir / "01_sequence_prevalence.tsv", prevalence_rows, [
        "canonical_sequence",
        "modality_group",
        "n_subjects",
        "n_total_subjects",
        "prevalence_pct",
        "role",
        "first_seen",
        "last_seen",
        "subjects",
        "raw_series_descriptions",
    ])

    # 02
    write_tsv(output_dir / "02_subject_protocol_review.tsv", subject_rows, [
        "subject",
        "session",
        "scan_date",
        "protocol_family",
        "n_original_kept_rows",
        "n_research_candidate_sequences",
        "research_sequence_set",
        "noncore_extra_sequence_set",
        "all_kept_sequence_set",
        "ordered_kept_series",
    ])

    # 03
    threshold_col = f"core_sequences_{int(core_threshold * 100)}pct"
    write_tsv(output_dir / "03_protocol_family_summary.tsv", family_rows, [
        "protocol_family",
        "n_subjects",
        "first_scan_date",
        "last_scan_date",
        "subjects",
        "core_sequences_100pct",
        threshold_col,
        "noncore_optional_or_extra_sequences",
    ])

    # 04
    write_tsv(output_dir / "04_excluded_series_audit.tsv", excluded_rows, [
        "subject",
        "session",
        "scan_date",
        "series_number",
        "series_description",
        "protocol_name",
        "image_type",
        "n_files",
        "exclude_reason",
    ])

    # Small README
    readme = f"""# Protocol review outputs

Generated by `review_series_protocols.py`.

Default outputs:
- `01_sequence_prevalence.tsv`: sequence-level prevalence across subjects.
- `02_subject_protocol_review.tsv`: subject-level source sequence sets and assigned family.
- `03_protocol_family_summary.tsv`: human-readable protocol family summaries.
- `04_excluded_series_audit.tsv`: excluded rows and reasons.

Core threshold: {core_threshold:.2f}

Rows kept for protocol discovery: {len(kept_rows)}
Rows excluded: {len(excluded_rows)}
Subjects/sessions reviewed: {len(subject_rows)}
Protocol families: {len(family_rows)}
"""
    (output_dir / "README.md").write_text(readme, encoding="utf-8")


def detect_mode(args) -> None:
    rows, _ = read_tsv(args.input)
    kept, excluded = prepare_rows(rows)
    grouped = group_by_subject(kept)
    subject_rows = build_subject_reviews(grouped)
    prevalence_rows = build_sequence_prevalence(subject_rows, kept, args.core_threshold)
    family_rows, _family_sequence_rows = build_family_summary(subject_rows, args.core_threshold, args.site)

    write_detect_outputs(
        args.output_dir,
        kept,
        excluded,
        subject_rows,
        prevalence_rows,
        family_rows,
        args.core_threshold,
    )

    print(f"[detect] input rows: {len(rows)}")
    print(f"[detect] kept ORIGINAL/source rows: {len(kept)}")
    print(f"[detect] excluded rows: {len(excluded)}")
    print(f"[detect] subjects/sessions: {len(subject_rows)}")
    print(f"[detect] protocol families: {len(family_rows)}")
    print(f"[detect] wrote: {args.output_dir}")


# -----------------------------
# identify mode
# -----------------------------

def parse_seq_list(value: str) -> Set[str]:
    value = value or ""
    if not value.strip():
        return set()
    return {x.strip() for x in value.split(" + ") if x.strip()}


def load_protocol_summary(path: Path, core_threshold: float) -> List[dict]:
    rows, _ = read_tsv(path)
    threshold_col = f"core_sequences_{int(core_threshold * 100)}pct"

    for row in rows:
        if threshold_col not in row or not row.get(threshold_col):
            # Fall back to first core_sequences_*pct column.
            for key in row.keys():
                if key.startswith("core_sequences_") and key.endswith("pct") and key != "core_sequences_100pct":
                    row[threshold_col] = row.get(key, "")
                    break
        row["_core_set"] = parse_seq_list(row.get(threshold_col) or row.get("core_sequences_100pct", ""))
    return rows


def identify_subject(subject_row: dict, protocol_rows: Sequence[dict]) -> Tuple[dict, List[dict]]:
    subj_set = parse_seq_list(subject_row["research_sequence_set"])
    scored = []

    for proto in protocol_rows:
        core = proto.get("_core_set", set())
        if not core:
            score = 0.0
            missing = set()
            extra = subj_set
        else:
            score = len(subj_set & core) / len(core)
            missing = core - subj_set
            extra = subj_set - core

        scored.append({
            "protocol_family": proto.get("protocol_family", ""),
            "score": round(score, 3),
            "n_core_expected": len(core),
            "n_core_present": len(subj_set & core),
            "missing_core_sequences": " + ".join(sorted(missing)),
            "extra_research_sequences": " + ".join(sorted(extra)),
        })

    scored.sort(key=lambda r: (-float(r["score"]), r["protocol_family"]))
    best = scored[0] if scored else {
        "protocol_family": "NO_PROTOCOL_SUMMARY",
        "score": 0.0,
        "n_core_expected": 0,
        "n_core_present": 0,
        "missing_core_sequences": "",
        "extra_research_sequences": "",
    }

    return best, scored


def identify_mode(args) -> None:
    rows, _ = read_tsv(args.input)
    kept, excluded = prepare_rows(rows)
    grouped = group_by_subject(kept)
    subject_rows = build_subject_reviews(grouped)

    if not subject_rows:
        raise SystemExit("ERROR: no source/original rows found for identify mode")

    protocols = load_protocol_summary(args.protocol_summary, args.core_threshold)

    identified = []
    all_scores = []

    for subj in subject_rows:
        best, scored = identify_subject(subj, protocols)
        subj["protocol_family"] = best["protocol_family"]
        subj["best_protocol_score"] = best["score"]
        subj["missing_core_sequences"] = best["missing_core_sequences"]
        subj["extra_research_sequences_vs_best"] = best["extra_research_sequences"]
        identified.append(subj)
        for row in scored:
            all_scores.append({
                "subject": subj["subject"],
                "session": subj["session"],
                "scan_date": subj["scan_date"],
                **row,
            })

    # In identify mode, still write the same four files, but protocol summary is a match summary.
    prevalence = build_sequence_prevalence(subject_rows, kept, args.core_threshold)

    write_tsv(args.output_dir / "01_sequence_prevalence.tsv", prevalence, [
        "canonical_sequence",
        "modality_group",
        "n_subjects",
        "n_total_subjects",
        "prevalence_pct",
        "role",
        "first_seen",
        "last_seen",
        "subjects",
        "raw_series_descriptions",
    ])

    write_tsv(args.output_dir / "02_subject_protocol_review.tsv", identified, [
        "subject",
        "session",
        "scan_date",
        "protocol_family",
        "best_protocol_score",
        "missing_core_sequences",
        "extra_research_sequences_vs_best",
        "n_original_kept_rows",
        "n_research_candidate_sequences",
        "research_sequence_set",
        "noncore_extra_sequence_set",
        "all_kept_sequence_set",
        "ordered_kept_series",
    ])

    # For identify mode, 03 is the score table against existing protocol families.
    write_tsv(args.output_dir / "03_protocol_family_summary.tsv", all_scores, [
        "subject",
        "session",
        "scan_date",
        "protocol_family",
        "score",
        "n_core_expected",
        "n_core_present",
        "missing_core_sequences",
        "extra_research_sequences",
    ])

    write_tsv(args.output_dir / "04_excluded_series_audit.tsv", excluded, [
        "subject",
        "session",
        "scan_date",
        "series_number",
        "series_description",
        "protocol_name",
        "image_type",
        "n_files",
        "exclude_reason",
    ])

    readme = f"""# Protocol identify outputs

Generated by `review_series_protocols.py --mode identify`.

Protocol summary used: {args.protocol_summary}

Outputs:
- `01_sequence_prevalence.tsv`: sequence prevalence within the input file.
- `02_subject_protocol_review.tsv`: best matching protocol family per subject.
- `03_protocol_family_summary.tsv`: score table against each known protocol family.
- `04_excluded_series_audit.tsv`: excluded rows and reasons.
"""
    (args.output_dir / "README.md").write_text(readme, encoding="utf-8")

    print(f"[identify] input rows: {len(rows)}")
    print(f"[identify] subjects/sessions: {len(subject_rows)}")
    print(f"[identify] protocol families compared: {len(protocols)}")
    print(f"[identify] wrote: {args.output_dir}")


# -----------------------------
# CLI
# -----------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Detect or identify prevalence-based MRI protocol families from series TSV inventories."
    )

    parser.add_argument("--input", required=True, type=Path, help="Input per-series TSV. Can be one subject or concatenated subjects.")
    parser.add_argument("--output-dir", required=True, type=Path, help="Directory for review TSV outputs.")
    parser.add_argument("--mode", choices=["detect", "identify"], default="detect", help="detect discovers protocol families; identify matches to an existing summary.")
    parser.add_argument("--concat", action="store_true", help="Input is a concatenated TSV. Used as an explicit reminder; behavior is inferred from subject/session columns.")
    parser.add_argument("--site", default="", help="Optional site/project prefix for detected family names, e.g. COMPASS.")
    parser.add_argument("--core-threshold", type=float, default=0.80, help="Prevalence threshold for core sequences within a family. Default: 0.80.")
    parser.add_argument("--protocol-summary", type=Path, default=None, help="Required for --mode identify: 03_protocol_family_summary.tsv from detect mode.")

    return parser


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)
    args.output_dir.mkdir(parents=True, exist_ok=True)

    if not args.input.exists():
        print(f"ERROR: input file does not exist: {args.input}", file=sys.stderr)
        return 2

    if not (0 < args.core_threshold <= 1):
        print("ERROR: --core-threshold must be between 0 and 1", file=sys.stderr)
        return 2

    if args.mode == "identify":
        if args.protocol_summary is None:
            print("ERROR: --protocol-summary is required in identify mode", file=sys.stderr)
            return 2
        if not args.protocol_summary.exists():
            print(f"ERROR: protocol summary not found: {args.protocol_summary}", file=sys.stderr)
            return 2
        identify_mode(args)
    else:
        detect_mode(args)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
